import type { StrategyReport } from "../analysis/schemas.js";

export function renderStrategyReportMarkdown(report: StrategyReport): string {
  return [
    `# ${report.date} 台股策略報告`,
    "",
    "## 1. 今日市場狀態",
    `- AI 模式：${report.cost_guard.ai_mode}`,
    "- 今日是否使用付費資料 API：否",
    `- 市場資料品質：${report.market.data_quality}`,
    `- 資料缺口：${report.data_gaps.length ? report.data_gaps.join("、") : "無"}`,
    "",
    "## 2. 多空判斷",
    `- 結論：${report.market.bias}`,
    `- 分數：${report.market.bias_score}`,
    `- 主要證據：${report.market.evidence.join("；") || "資料不足"}`,
    "",
    "## 3. 可能走勢",
    "| 情境 | 信心 | 確認訊號 | 失效訊號 |",
    "|---|---:|---|---|",
    ...report.market.likely_paths.map((path) => `| ${path.scenario} | ${path.confidence_score} | ${path.confirmation.join("、")} | ${path.rejection.join("、")} |`),
    "",
    "## 4. 大戶策略推估",
    `- 判斷：${report.market.smart_money_phase}`,
    `- 信心：${report.market.smart_money_confidence}`,
    `- 依據：${report.market.evidence.join("；") || "資料不足"}`,
    "",
    "## 5. 強勢族群",
    "| 排名 | 族群 | 階段 | 代表股 | 風險 |",
    "|---:|---|---|---|---|",
    ...report.sectors.map((sector, index) => `| ${index + 1} | ${sector.theme} | ${sector.phase} | ${sector.leaders.join("、")} | ${sector.risk.join("、")} |`),
    "",
    "## 6. 續抱觀察",
    "| 股票 | 建議 | 支撐 | 壓力 | 停損 | 理由 |",
    "|---|---|---:|---:|---:|---|",
    ...report.holdings.map((holding) => `| ${holding.ticker} ${holding.name} | ${holding.decision} | ${holding.key_supports.join(" / ")} | ${holding.key_resistances.join(" / ")} | ${holding.stop_loss} | ${holding.reason.join("、")} |`),
    "",
    "## 7. 當沖候選",
    "| 股票 | 多/空 | 進場觸發 | 建議進場 | 停損 | 停利 | 信心 |",
    "|---|---|---|---:|---:|---:|---:|",
    ...report.daytrade_candidates.map((plan) => `| ${plan.ticker} ${plan.name} | ${plan.side} | ${plan.setup} | ${plan.entry_zone.price_min}-${plan.entry_zone.price_max} | ${plan.stop_loss.price} | ${plan.take_profit.price_min}-${plan.take_profit.price_max} | ${plan.confidence_score} |`),
    "",
    "## 8. 波段候選",
    "| 股票 | 階段 | 買點 | 停損 | 目標 | 風險 |",
    "|---|---|---:|---:|---:|---|",
    ...report.swing_candidates.map((stock) => `| ${stock.ticker} ${stock.name} | ${stock.stage} | 等回測確認 | - | - | 風險分數 ${stock.risk_score} |`),
    "",
    "## 9. 風險警訊",
    ...(report.risk_alerts.length ? report.risk_alerts.map((alert) => `- [${alert.level}] ${alert.ticker ? `${alert.ticker} ` : ""}${alert.message}`) : ["- 無"]),
    "",
    "## 10. 資料缺口",
    ...(report.data_gaps.length ? report.data_gaps.map((gap) => `- ${gap}`) : ["- 無"]),
    "",
    "## 11. 明日觀察重點",
    ...report.news_impact.map((item) => `- ${item.title}：${item.market_direction}，信心 ${item.confidence_score}`),
    ...(report.news_impact.length ? [] : ["- 等待官方資料與 LINE manual news 更新"]),
    "",
    report.disclaimer
  ].join("\n");
}
